version: '3'

services:
  qdrant_database:
    container_name: qdrant
    image: qdrant/qdrant
    ports:
      - 6333:6333
#    volumes:
#      # Just specify a path and let the Engine create a volume
#      - /container/qdrant
#    volumes:
#      - qdrant_volume: /var/lib/docker/qdrant
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 300M

  main_stream:
    image: llamaindex-project
    container_name: llamaindex-project
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 300M
#
#
#volumes:
#  qdrant_volume:

