version: '3'

services:
  qdrant_database:
    container_name: qdrant
    image: qdrant/qdrant
    ports:
      - 6333:6333

#    volumes:
#      - qdrant-volume: /var/lib/docker/qdrant

  main_stream:
    image: llamaindex-project
    container_name: llamaindex-project
    network_mode: host



#volumes:
#  qdrant_volume:
