version: '3'

services:
  qdrant_database:
    container_name: qdrant
    image: qdrant/qdrant
    build: .
    volumes:
      - ./qdrant_volume/data:/qdrant_volume/data
    ports:
      - 6333:6333

    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 300M

  main_stream:
    image: llamaindex-project
    container_name: llamaindex-project
#    networks:
#      - webnet
    network_mode:
      host
    build: .
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 300M
#    ports:
#      - 8501:8501
#
#
volumes:
  qdrant_volume:

