version: '3'

services:
  qdrant_database:
    container_name: qdrant
    image: qdrant/qdrant
    build: .
    volumes:
      - "./data/qdrant_data:/qdrant/storage"
    ports:
      - ${QDRANT_PORT}:6333

    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 300M

  main_stream:
    image: llamaindex-project
    container_name: llamaindex-project
    network_mode: host
    build: .
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 300M
#
#
volumes:
  qdrant_volume:

